"""GraphBuilder — assembles a LangGraph StateGraph from the parsed project structure."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any, Callable

from ..models.graph import GraphStructure, RoutingType, SubgraphDef
from ..models.node import CompiledNode
from ..models.prompt import ParsedPrompt
from ..models.schema import SchemaModel


# State key where node outputs are stored
NODE_OUTPUTS_KEY = "node_outputs"
ERRORS_KEY = "errors"


class GraphBuilder:
    def __init__(
        self,
        parsed_prompts: dict[str, ParsedPrompt],
        folder_tree: SubgraphDef,
        schema_registry: dict[str, type] | None = None,
        source_registry: dict[str, Any] | None = None,
        project_name: str = "abt_project",
    ):
        self.parsed_prompts = parsed_prompts
        self.tree = folder_tree
        self.schemas = schema_registry or {}
        self.sources = source_registry or {}
        self.project_name = project_name

    def build_structure(self) -> GraphStructure:
        """Build the full GraphStructure (metadata + compiled nodes + dependency graph)."""

        # Resolve compiled nodes
        all_nodes: dict[str, CompiledNode] = {}
        for qualified_name, prompt in self.parsed_prompts.items():
            node = self._compile_node(qualified_name, prompt)
            all_nodes[qualified_name] = node

        # Build dependency graph from ref() calls
        dep_graph: dict[str, set[str]] = {}
        for qualified_name, node in all_nodes.items():
            deps = set()
            for dep_name in node.prompt.raw_dependencies:
                # Find which qualified node has this name as its leaf
                resolved = self._resolve_prompt_ref(dep_name, all_nodes)
                if resolved:
                    deps.add(resolved)
            dep_graph[qualified_name] = deps

        return GraphStructure(
            project_name=self.project_name,
            root=self.tree,
            all_nodes=all_nodes,
            all_schemas=self.schemas,
            all_sources=self.sources,
            dependency_graph=dep_graph,
        )

    def _compile_node(self, qualified_name: str, prompt: ParsedPrompt) -> CompiledNode:
        output_schema = None
        if prompt.config.output_schema and prompt.config.output_schema in self.schemas:
            output_schema = self.schemas[prompt.config.output_schema]

        llm_config = {
            "model": prompt.config.model,
            "temperature": prompt.config.temperature,
            "max_tokens": prompt.config.max_tokens,
        }

        return CompiledNode(
            name=prompt.name,
            qualified_name=qualified_name,
            prompt=prompt,
            output_schema_type=output_schema,
            resolved_tools=[f"{s}.{t}" for s, t in prompt.raw_source_refs],
            on_fail_target=prompt.config.on_fail_route,
            max_retries=prompt.config.max_retries,
            llm_config=llm_config,
        )

    def _resolve_prompt_ref(
        self, dep_name: str, all_nodes: dict[str, CompiledNode]
    ) -> str | None:
        """Resolve a ref('name') to a qualified node path."""
        # Exact match against qualified name
        if dep_name in all_nodes:
            return dep_name
        # Match against leaf name
        for qualified, node in all_nodes.items():
            if node.name == dep_name:
                return qualified
        return None

    def generate_python_code(self, graph_structure: GraphStructure, output_path: Path) -> str:
        """Generate a standalone runnable Python script from the compiled graph."""

        lines = []
        lines.append("# -*- coding: utf-8 -*-")
        lines.append('"""Auto-generated by abt compile. Run with: python this_file.py"""')
        lines.append("")
        lines.append("import asyncio")
        lines.append("import json")
        lines.append("from pathlib import Path")
        lines.append("from typing import Any, Literal, Optional, Annotated")
        lines.append("")
        lines.append("from typing_extensions import TypedDict")
        lines.append("from pydantic import BaseModel, Field, create_model")
        lines.append("from langgraph.graph import StateGraph, START, END")
        lines.append("from langgraph.graph.message import add_messages")
        lines.append("")
        lines.append(f"# Project: {graph_structure.project_name}")
        lines.append(f"# Nodes: {len(graph_structure.all_nodes)}")
        lines.append(f"# Sources: {len(graph_structure.all_sources)}")
        lines.append("")

        # Emit schema models
        for schema_name, model_cls in graph_structure.all_schemas.items():
            schema_json = json.dumps(model_cls.model_json_schema(), indent=2)
            lines.append(f"# Schema: {schema_name}")
            lines.append(f"SCHEMA_{schema_name.upper()} = {schema_json!r}")
            lines.append("")

        # Emit node configs
        lines.append("# Node configurations")
        lines.append("NODE_CONFIGS = {")
        for qualified, node in graph_structure.all_nodes.items():
            lines.append(f"    {qualified!r}: {{")
            lines.append(f"        'system_prompt': {node.prompt.system_prompt!r},")
            lines.append(f"        'output_schema': {node.prompt.config.output_schema!r},")
            lines.append(f"        'tools': {node.resolved_tools},")
            lines.append(f"        'max_retries': {node.max_retries},")
            lines.append(f"        'max_tool_calls': {node.prompt.config.max_tool_calls},")
            lines.append(f"        'output_columns': {node.prompt.output_columns},")
            lines.append(f"    }},")
        lines.append("}")
        lines.append("")

        # Emit graph structure
        lines.append("# Graph structure")
        lines.append("GRAPH_NODES = [")
        for qualified in graph_structure.all_nodes:
            lines.append(f"    {qualified!r},")
        lines.append("]")
        lines.append("")
        lines.append("GRAPH_DEPENDENCIES = {")
        for qualified, deps in graph_structure.dependency_graph.items():
            if deps:
                lines.append(f"    {qualified!r}: {list(deps)},")
        lines.append("}")
        lines.append("")

        # Emit routing tree
        lines.append(f"ROUTING_TREE = {json.dumps(_subgraph_to_dict(graph_structure.root), indent=2)}")
        lines.append("")

        # Emit routing type enum and flatten logic
        lines.extend([
            "",
            "ROUTING_SEQUENTIAL = 'sequential'",
            "ROUTING_REQUIRE_ALL = 'require_all'",
            "ROUTING_REQUIRE_ANY = 'require_any'",
            "",
            "",
            "def _flatten_blocks(tree):",
            "    \"\"\"Produce recursively nested execution blocks from a routing tree.",
            "",
            "    SEQUENTIAL children are expanded inline. REQUIRE_ALL/REQUIRE_ANY",
            "    children become nested blocks compiled as LangGraph subgraphs.",
            "    \"\"\"",
            "    result = []",
            "    for child in tree.get('subgraphs', []):",
            "        routing = child.get('routing', ROUTING_SEQUENTIAL)",
            "        if routing == ROUTING_SEQUENTIAL:",
            "            result.extend(_flatten_blocks(child))",
            "        elif routing == ROUTING_REQUIRE_ALL:",
            "            result.append({'type': 'parallel', 'name': child['name'],",
            "                           'children': _flatten_blocks(child)})",
            "        elif routing == ROUTING_REQUIRE_ANY:",
            "            result.append({'type': 'any', 'name': child['name'],",
            "                           'children': _flatten_blocks(child)})",
            "    for node_name in tree.get('nodes', []):",
            "        result.append({'type': 'node', 'name': node_name})",
            "    return result",
            "",
        ])

        # Emit AbtState and build_graph
        lines.extend([
            "",
            "def _merge_dicts(left, right):",
            "    return {**left, **right}",
            "",
            "",
            "def _block_entry_names(block):",
            '    """Entry node name for a block."""',
            "    return [block['name']]",
            "",
            "",
            "def _block_exit_names(block):",
            '    """Exit node name for a block."""',
            "    return [block['name']]",
            "",
            "",
            "def _collect_leaf_names(blocks):",
            '    """Recursively collect all leaf node names from nested blocks."""',
            "    result = []",
            "    for b in blocks:",
            "        if b['type'] == 'node':",
            "            result.append(b['name'])",
            "        else:",
            "            result.extend(_collect_leaf_names(b.get('children', [])))",
            "    return result",
            "",
            "",
            "def _add_node_to(sg, node_name):",
            '    """Add a leaf placeholder node to the StateGraph."""',
            "    def make_node_fn(name):",
            "        def node_fn(state) -> dict:",
            "            print(f'[abt] Running: {name}')",
            "            return {'node_outputs': {name: {'status': 'ok'}}}",
            "        return node_fn",
            "    sg.add_node(node_name, make_node_fn(name=node_name))",
            "",
            "",
            "def _wire_fan_out_in(sg, children):",
            '    """Wire AND-gate: START -> all entries, all exits -> END."""',
            "    for child in children:",
            "        for entry in _block_entry_names(child):",
            "            sg.add_edge(START, entry)",
            "        for exit_name in _block_exit_names(child):",
            "            sg.add_edge(exit_name, END)",
            "",
            "",
            "def _wire_or_gate(sg, block):",
            '    """Wire OR-gate: START -> children -> collector -> END."""',
            "    collector_name = block['name'] + '__collector'",
            "    leaf_names = _collect_leaf_names(block['children'])",
            "    def make_collector(names):",
            "        def collector_fn(state) -> dict:",
            '            outputs = state.get("node_outputs", {})',
            '            for n in names:',
            '                out = outputs.get(n, {})',
            '                if out and "error" not in out:',
            "                    return {}",
            '            return {"errors": [f"require_any block: all nodes failed"]}',
            "        return collector_fn",
            "    sg.add_node(collector_name, make_collector(list(leaf_names)))",
            "    for child in block['children']:",
            "        for entry in _block_entry_names(child):",
            "            sg.add_edge(START, entry)",
            "        for exit_name in _block_exit_names(child):",
            "            sg.add_edge(exit_name, collector_name)",
            "    sg.add_edge(collector_name, END)",
            "",
            "",
            "def _wire_sequential(sg, blocks):",
            '    """Wire START -> blocks[0] -> ... -> END sequentially."""',
            "    if not blocks:",
            "        sg.add_edge(START, END)",
            "        return",
            "    for entry in _block_entry_names(blocks[0]):",
            "        sg.add_edge(START, entry)",
            "    for i in range(len(blocks) - 1):",
            "        for src in _block_exit_names(blocks[i]):",
            "            for tgt in _block_entry_names(blocks[i + 1]):",
            "                sg.add_edge(src, tgt)",
            "    for exit_name in _block_exit_names(blocks[-1]):",
            "        sg.add_edge(exit_name, END)",
            "",
            "",
            "def _build_graph_recursive(sg, blocks, is_top_level=False):",
            '    """Recursively add nodes and compiled subgraphs to sg."""',
            "    for block in blocks:",
            "        if block['type'] == 'node':",
            "            _add_node_to(sg, block['name'])",
            "        elif block['type'] in ('parallel', 'any'):",
            "            child_sg = StateGraph(AbtState)",
            "            _build_graph_recursive(child_sg, block['children'])",
            "            if block['type'] == 'parallel':",
            "                _wire_fan_out_in(child_sg, block['children'])",
            "            else:",
            "                _wire_or_gate(child_sg, block)",
            "            sg.add_node(block['name'], child_sg.compile())",
            "    if is_top_level:",
            "        _wire_sequential(sg, blocks)",
            "",
            "",
            "def _collect_wired_names(blocks, result_set):",
            '    """Recursively collect all wired node names from blocks."""',
            "    for b in blocks:",
            "        if b['type'] == 'node':",
            "            result_set.add(b['name'])",
            "        else:",
            "            result_set.add(b['name'])",
            "            _collect_wired_names(b.get('children', []), result_set)",
            "",
            "",
            "class AbtState(TypedDict, total=False):",
            "    messages: Annotated[list, add_messages]",
            "    node_outputs: Annotated[dict, _merge_dicts]",
            "    errors: list",
            "",
            "",
            "def build_graph():",
            '    """Build and return the compiled LangGraph StateGraph."""',
            "",
            "    sg = StateGraph(AbtState)",
            "    blocks = _flatten_blocks(ROUTING_TREE)",
            "    _build_graph_recursive(sg, blocks, is_top_level=True)",
            "",
            "    wired = set()",
            "    _collect_wired_names(blocks, wired)",
            "    for node_name in GRAPH_NODES:",
            "        if node_name not in wired:",
            "            sg.add_edge(START, node_name)",
            "            sg.add_edge(node_name, END)",
            "",
            "    return sg.compile()",
            "",
            "",
            "async def main():",
            "    import sys",
            "    graph = build_graph()",
            "    initial_state = {'messages': []}",
            "    if len(sys.argv) > 1:",
            "        with open(sys.argv[1]) as f:",
            "            initial_state.update(json.load(f))",
            "    result = graph.invoke(initial_state)",
            "    print(json.dumps(result.get('node_outputs', {}), indent=2))",
            "",
            "",
            "if __name__ == '__main__':",
            "    asyncio.run(main())",
        ])

        code = "\n".join(lines)
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(code, encoding="utf-8")
        return code


def _subgraph_to_dict(sg: SubgraphDef) -> dict:
    return {
        "name": sg.name,
        "folder_name": sg.folder_name,
        "routing": sg.routing.value,
        "metadata": sg.metadata,
        "nodes": sg.nodes,
        "subgraphs": [_subgraph_to_dict(s) for s in sg.subgraphs],
    }
